version: '3.5'

services:
  bot:
    image: otimofie/tennis_bot
    environment:
      TOKEN: 8088613497:AAEIgpbucvx0cdxHj5YelwPbrv0mvRM9VhA
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
    depends_on: 
      - db
    restart: always
    ports:
      - "8080:8080"
      - "9090:9090"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    # volumes:
    #   - ./data:/var/lib/postgresql/data


  